# Generated by Django 5.0.3 on 2024-03-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0001_CREACION_TABLAS_COLEGIO'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
